--AN OVERVIEW OF THE DATASET 
SELECT*
FROM FASHION_PRODUCTS;

-- GETTING UNIQUE VALUES TO AID DECISION
SELECT DISTINCT PRODUCT_NAME
FROM FASHION_PRODUCTS;

SELECT DISTINCT BRAND
FROM FASHION_PRODUCTS;

SELECT DISTINCT CATEGORY
FROM FASHION_PRODUCTS;

SELECT DISTINCT COLOR
FROM FASHION_PRODUCTS;

SELECT DISTINCT SIZE
FROM FASHION_PRODUCTS;

--DATA ANALYSIS (EACH BRAND PRODUCES ALL FIVE UNIQUE PRODUCTS)

--PRODUCT ANALYSIS (FROM THE MOST EXPENSIVE TO THE LEAST EXPENSIVE)

--AVERAGE PRICE OF EACH PRODUCT ACROSS ALL BRANDS
SELECT BRAND,PRODUCT_NAME,AVG(PRICE) AS AVG_PRICE
FROM FASHION_PRODUCTS
GROUP BY PRODUCT_NAME,BRAND
ORDER BY PRODUCT_NAME, AVG_PRICE DESC;

--AVERAGE PRICE OF EACH CATEGORY ACROSS ALL BRANDS
SELECT BRAND,CATEGORY,AVG(PRICE) AS AVG_PRICE
FROM FASHION_PRODUCTS
GROUP BY CATEGORY,BRAND
ORDER BY CATEGORY, AVG_PRICE DESC;

--CONSUMER PREFERENCE

--AVERAGE RATING OF EACH PRODUCT ACROSS ALL BRANDS
SELECT BRAND,PRODUCT_NAME,ROUND(AVG(RATING),3) AS AVG_RATING
FROM FASHION_PRODUCTS
GROUP BY PRODUCT_NAME,BRAND
ORDER BY PRODUCT_NAME, AVG_RATING DESC;

--SALES COUNT OF EACH PRODUCT ACROSS ALL BRANDS
SELECT BRAND,PRODUCT_NAME,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
GROUP BY PRODUCT_NAME,BRAND
ORDER BY PRODUCT_NAME, SALES_COUNT DESC;

--DRILL THROUGH TO PREFERENCE BY COLOR (DRESS)
SELECT BRAND,COLOR,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
WHERE PRODUCT_NAME = 'DRESS'
GROUP BY BRAND,COLOR
ORDER BY SALES_COUNT DESC, COLOR;

--DRILL THROUGH TO PREFERENCE BY COLOR (JEANS)
SELECT BRAND,COLOR,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
WHERE PRODUCT_NAME = 'JEANS'
GROUP BY BRAND,COLOR
ORDER BY SALES_COUNT DESC, COLOR;

--DRILL THROUGH TO PREFERENCE BY COLOR (SHOES)
SELECT BRAND,COLOR,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
WHERE PRODUCT_NAME = 'SHOES'
GROUP BY BRAND,COLOR
ORDER BY SALES_COUNT DESC, COLOR;

--DRILL THROUGH TO PREFERENCE BY COLOR (SWEATER)
SELECT BRAND,COLOR,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
WHERE PRODUCT_NAME = 'SWEATER'
GROUP BY BRAND,COLOR
ORDER BY SALES_COUNT DESC, COLOR;

--DRILL THROUGH TO PREFERENCE BY COLOR (T-SHIRT)
SELECT BRAND,COLOR,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
WHERE PRODUCT_NAME = 'T-SHIRT'
GROUP BY BRAND,COLOR
ORDER BY SALES_COUNT DESC, COLOR;

--BRAND ANALSYSIS
SELECT PRODUCT_NAME,COLOR,SIZE,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
WHERE BRAND = 'ADIDAS'
GROUP BY PRODUCT_NAME,COLOR,SIZE
ORDER BY PRODUCT_NAME,COLOR,SIZE;

SELECT PRODUCT_NAME,COLOR,SIZE,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
WHERE BRAND = 'GUCCI'
GROUP BY PRODUCT_NAME,COLOR,SIZE
ORDER BY PRODUCT_NAME,COLOR,SIZE;

SELECT PRODUCT_NAME,COLOR,SIZE,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
WHERE BRAND = 'H&M'
GROUP BY PRODUCT_NAME,COLOR,SIZE
ORDER BY PRODUCT_NAME,COLOR,SIZE;

SELECT PRODUCT_NAME,COLOR,SIZE,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
WHERE BRAND = 'NIKE'
GROUP BY PRODUCT_NAME,COLOR,SIZE
ORDER BY PRODUCT_NAME,COLOR,SIZE;

SELECT PRODUCT_NAME,COLOR,SIZE,COUNT(PRODUCT_ID) AS SALES_COUNT
FROM FASHION_PRODUCTS
WHERE BRAND = 'ZARA'
GROUP BY PRODUCT_NAME,COLOR,SIZE
ORDER BY PRODUCT_NAME,COLOR,SIZE;


